### ISSUE TITLE
Konten React-Native-Firebase-Messaging dan Push Notification Masih Kosong

### ISSUE THREAD

**Issue by reyn-nova** [crocodication/guide_for_react_native_libraries#20]
Library ini salah satu yang konfigurasi nya perlu step2 berulang yang kadang sering keliru, konten readme untuk ini diperlukan agar next di project untuk setup tinggal hanya ikuti setup yang biasa kita gunakan aja

**Comment by nahansans** [comment]
Besok tak lanjutin, beberapa step²nya ada yang agak bingung makanya belum tak edit readme nya kak

**Comment by reyn-nova** [comment]
solved in #26
