### ISSUE TITLE
Terdapat simbol backtick 3 kali di file js, padahal bukan file md

### ISSUE THREAD

**Issue by reyn-nova** [crocodication/guide_for_react_native_libraries#9]
ketinggalan @nahansans di [folder ini](https://github.com/crocodication/guide_for_react_native_libraries/tree/master/react-navigation-and-stack-navigator/example) di file App.js, Splashscreen.js dan Home.js ada symbol backtick tiga kali padahal itu bukan file markdown tapi memang murni js

**Comment by nahansans** [comment]
done @rynvva

**Comment by reyn-nova** [comment]
oke solved in #8 #10 dan #11 thanks @nahansans
